url: https://conink.github.io
baseurl:

# Site settings
title: InvisiSwitch
email: conductiveinkdtu@gmail.com
description: "Landing page for project InvisiSwitch"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Carsten Fjord
  pic: carsten
  position: Design & Innovation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://dk.linkedin.com/pub/carsten-keinicke-fjord-christensen/70/215/984

- name: Dinesan Rasiah
  pic: dinesan
  position: Design & Innovation
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://dk.linkedin.com/in/dinesan/da

- name: Albert Davidsen
  pic: albert
  position: Electrical Engineering
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
    - title: linkedin
      url: https://dk.linkedin.com/pub/albert-wieck-davidsen/42/79/a71/da

- name: Kasper Duong
  pic: kasper
  position: Computer Science and Engineering
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: https://dk.linkedin.com/pub/kasper-duong/70/238/187
    - title: github
      url: https://github.com/dxong

- name: Mark Ian Svenningsen
  pic: mark
  position: Computer Science and Engineering
  social:
    - title: linkedin
      url: https://dk.linkedin.com/pub/mark-ian-svenningsen/4b/948/177/da
    - title: github
      url: https://github.com/masve
    - title: bitbucket
      url: http://bitbucket.org/masve

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/conink

# Postal address (add as many lines as necessary)
address:
  - line: DTU Skylab
  - line: 2800 Kongens Lyngby

# Build settings
markdown: kramdown
permalink: pretty
